# 
policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/g1/policy_amp_new.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/g1_description/scene.xml"

# Total simulation time
simulation_duration: 160.0
# Simulation time step
simulation_dt: 0.001
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 20

kps: [200., 150., 150., 200.,  40.,  40., 200., 150., 150., 200.,  40.,  40.,
        200.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.]
kds: [4., 3., 3., 4., 2., 2., 4., 3., 3., 4., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2.]
# kps: [150, 150, 200, 200, 40, 40,150, 150, 200, 200, 40, 40]
# kds: [5, 5,5, 5, 4, 4,5, 5,5, 5, 4, 4]

default_angles: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0, 
                  -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,0.,0,0,0,0,0,0,0,0]
# default_angles: [-0.4,  0.0,  0.0,  0.8, -0.4, 0.0, 
#                   -0.4,  0.0,  0.0,  0.8, -0.4, 0.0]
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 21
num_obs: 72
frame: 10

cmd_init: [0., 0, 0]