# 
policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/irmv/policy_test3.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/irmv/test_copycopy.xml"

# Total simulation time
simulation_duration: 6.0
# Simulation time step
simulation_dt: 0.001
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 20

kps: [100, 100, 200, 200, 50, 100, 100, 200, 200, 50]
kds: [2, 2, 4, 4, 2,2, 2, 4, 4, 2]
# kps: [150, 150, 200, 200, 40, 40,150, 150, 200, 200, 40, 40]
# kds: [5, 5,5, 5, 4, 4,5, 5,5, 5, 4, 4]

default_angles: [0.,  0.0,  0.0,  0., 0.,
                  0.,  0.0,  0.0,  0., 0.]
# default_angles: [-0.4,  0.0,  0.0,  0.8, -0.4, 0.0, 
#                   -0.4,  0.0,  0.0,  0.8, -0.4, 0.0]
ang_vel_scale: 1. #0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 1.]
num_actions: 10
num_obs: 32
frame: 10

cmd_init: [0., 0, 0]